In [1]:
#grande quantidade de dados se assemelha a lista mas tem mais "poder"
#numpy é escrito em C

In [2]:
#https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

** O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como**

## Modelos de Machine Learning
## Processamento de Imagem e Computação Gráfica
## Tarefas matemáticas

** Instalar a biblioteca caso não tennha
** py -m pip install numpy

In [3]:
import numpy as np

In [4]:
v  = [1,2,3,4]

In [5]:
arr = np.array(v)

In [6]:
type(arr)

numpy.ndarray

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distribu

In [14]:
arr[0]

1

In [22]:
arr

array([1, 2, 3, 4])

In [13]:
print(arr)

[1 2 3 4]


In [15]:
for i in arr:
    print(i)

1
2
3
4


In [16]:
for i,j in enumerate(arr):
    print(i,j)

0 1
1 2
2 3
3 4


In [17]:
lista_lista = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
lista_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
m_numpy = np.array(lista_lista)

In [25]:
m_numpy[0][0]

1

In [35]:
m_numpy[:2][0]

array([1, 2, 3])

In [36]:
v = list(range(10))

In [37]:
v

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
arr = np.arange(10)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#como ver a ordem da matriz(linha,coluna)

In [40]:
arr.shape

(10,)

In [42]:

m_numpy.shape

(3, 3)

In [47]:
#passar uma tupla como argumento
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
arr_3  = np.zeros((3,3,3))

In [50]:
arr_3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
arr_3.shape

(3, 3, 3)

In [54]:
arr_x = np.zeros((2,3,4))

In [55]:
arr_x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [56]:
arr = np.zeros((2,3,4,5,6,7))

In [57]:
arr

array([[[[[[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ...,

In [59]:
np.ones(3)

array([1., 1., 1.])

In [60]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [63]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
#setando valores em uma matriz já criada

In [66]:
arr = np.eye(3)

In [67]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr[0][2] = 3

In [69]:
arr

array([[1., 0., 3.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
arr[2][1] = 5

In [71]:
arr

array([[1., 0., 3.],
       [0., 1., 0.],
       [0., 5., 1.]])

In [72]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
#mudando a ordem da matriz

In [74]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [88]:
a = [1]

In [89]:
b = a.copy()

In [90]:
b[0] = b[0] + 1

In [91]:
a

[1]

In [92]:
b

[2]

In [97]:
def test(v):
    for i,j in enumerate(v):
        v[i] = v[i] * 1000

In [98]:
x = [1,2,3,4,5]

In [99]:
test(x)

In [100]:
x

[1000, 2000, 3000, 4000, 5000]

In [110]:
arr = np.arange(5)

In [111]:
arr2 = arr.copy()

In [112]:
arr2[0] = 112391829

In [113]:
arr2

array([112391829,         1,         2,         3,         4])

In [114]:
arr

array([0, 1, 2, 3, 4])

In [116]:
arr = np.arange(20).reshape(5,4)

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [119]:
arr[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [120]:
arr[:,0]

array([ 0,  4,  8, 12, 16])

In [122]:
arr[3:,2:]

array([[14, 15],
       [18, 19]])

In [123]:
arr[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [124]:
v = [1,2,3,4]

In [125]:
2 in v

True

In [126]:
5 in v

False

In [127]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [135]:
arr2 = np.arange(9).reshape(3,3)

In [136]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
9 in arr

True

In [129]:
34 in arr

False

In [132]:
arr = np.arange(4)

In [133]:
arr

array([0, 1, 2, 3])

In [134]:
arr + 4

array([4, 5, 6, 7])

In [137]:
arr2 + 4

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
arr - 10

array([-10,  -9,  -8,  -7])

In [139]:
arr2 - 10

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [140]:
arr * 2

array([0, 2, 4, 6])

In [141]:
arr2 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [143]:
[1,2] * 3

[1, 2, 1, 2, 1, 2]

In [142]:
'a' * 30 

'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

In [144]:
arr / 2

array([0. , 0.5, 1. , 1.5])

In [145]:
arr2 / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [147]:
arr / 0

C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\envs\curso_python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\envs\curso_python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf])

In [148]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [149]:
np.sqrt(arr2)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [150]:
arr

array([0, 1, 2, 3])

In [151]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
np.sum(arr)

6

In [153]:
np.sum(arr2)

36

In [154]:
arr.sum()

6

In [155]:
arr2.sum()

36

In [156]:
np.mean(arr)

1.5

In [157]:
np.mean(arr2)

4.0

In [158]:
np.std(arr)

1.118033988749895

In [159]:
np.std(arr2)

2.581988897471611

In [160]:
#operações com linha e coluna

In [161]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [162]:
arr2.sum(axis=0)

array([ 9, 12, 15])

In [163]:
arr2.sum(axis=1)

array([ 3, 12, 21])

In [166]:
arr2.mean(axis=1)

array([1., 4., 7.])

In [167]:
arr2.mean(axis=0)

array([3., 4., 5.])